### ISSUE TITLE
Due does not have availableForWrite

### ISSUE THREAD

**Issue by ttlappalainen** [KimBP/NMEA0183#2]
Do you have any idea how we could use stream instead of hardwareSerial? In due hardwareSerial does not have function availableForWrite, so it does not compile my project. I tried to google non blocking stream, but was no success.

**Comment by KimBP** [comment]
To be honest I don't know.

Is Due special somehow? Doesn't it use standard arduino installation?

What version of arduino are you using?

I'm using version 1.6.9 but if I look into the core files for version 
1.0.5 which is default for ubuntu I don't have it neither.

The availableForWrite() function is not surrounded by any ifdef's or 
similar.

**Comment by ttlappalainen** [comment]
Hi,

It exist on due but definition is missing on SAM HardwareSerial.h, which is just abstract class. Definition exist on UARTCalss.h, which inherits HardwareSerial. So this causes that
if ( Serial3.availableForWrite()>0 ) ... compiles
but
HardwareSerial *port;
port=&Serial3
if ( port->availableForWrite()>0 ) ... does not.

So I have to open issue to add virtual int availableForWrite(void) = 0; to HardwareSerial.h
